version: '3'

volumes:
  localstack: {}

services:
  ##
  # Provide local faux AWS services.
  localstack:
    image: localstack/localstack
    environment:
      SERVICES: dynamodb,kinesis
    ports:
    - "4568" # Kinesis
    - "4569" # DynamoDB
    - "8080" # Web UI
    volumes:
    - "localstack:/tmp/localstack/data"
