version: '3'

volumes:
  kinesis: {}
  dynamodb: {}
  cloudwatch: {}

services:
  ##
  # Provide local faux AWS services.
  kinesis:
    image: localstack/localstack
    environment:
      SERVICES: kinesis:443
      USE_SSL: 1
    ports:  # We need very standard-looking endpoint urls
    - "443" # because we can't override the aws client endpoint
    volumes:
    - "kinesis:/tmp/localstack/data"
  dynamodb:
    image: localstack/localstack
    environment:
      SERVICES: dynamodb:443
      USE_SSL: 1
    ports:  # We need very standard-looking endpoint urls
    - "443" # because we can't override the aws client endpoint
    volumes:
    - "dynamodb:/tmp/localstack/data"
  cloudwatch:
    image: localstack/localstack
    environment:
      SERVICES: cloudwatch:443
      USE_SSL: 1
    ports:  # We need very standard-looking endpoint urls
    - "443" # because we can't override the aws client endpoint
    volumes:
    - "cloudwatch:/tmp/localstack/data"
  demo:
    build: context
    command: /srv/kcl-demo-setup
    environment:
      AWS_ACCESS_KEY_ID: demo
      AWS_SECRET_ACCESS_KEY: demo
      AWS_CBOR_DISABLE: 1
      KCL_EXTRA_ARGS: "-Dcom.amazonaws.sdk.disableCertChecking"
      KCL_PROPERTIES_FILE: /srv/demo.properties
    links:
    - kinesis:kinesis.us-east-1.amazonaws.com
    - dynamodb:dynamodb.us-east-1.amazonaws.com
    - cloudwatch:monitoring.us-east-1.amazonaws.com
    volumes:
    - "$PWD/demo:/srv"
