version: '3'

volumes:
  kinesis: {}
  dynamodb: {}

services:
  ##
  # Provide local faux AWS services.
  kinesis:
    image: localstack/localstack
    environment:
      SERVICES: kinesis:443
      USE_SSL: 1
    ports:  # We need very standard-looking endpoint urls
    - "443" # because we can't override the aws client endpoint
    volumes:
    - "kinesis:/tmp/localstack/data"
  dynamodb:
    image: localstack/localstack
    environment:
      SERVICES: dynamodb:443
      USE_SSL: 1
    ports:  # We need very standard-looking endpoint urls
    - "443" # because we can't override the aws client endpoint
    volumes:
    - "dynamodb:/tmp/localstack/data"
  demo:
    build: .
    command: bash -o vi
    environment:
      AWS_ACCESS_KEY_ID: demo
      AWS_SECRET_ACCESS_KEY: demo
    links:
    - kinesis:kinesis.us-east-1.amazonaws.com
    - dynamodb:dynamodb.us-east-1.amazonaws.com
